# Generated by Django 3.2.4 on 2021-07-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctioncategory_bid_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imagePath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
