# Generated by Django 3.2.4 on 2021-07-02 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
