# Generated by Django 3.2.4 on 2021-07-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_watchlisters'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_highest_bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='listings_highest', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='listings_won', to='auctions.user'),
            preserve_default=False,
        ),
    ]
